version: '3.8'

services:
  # Go 应用服务
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - app-network

  # MySQL 服务
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: user114514
      MYSQL_PASSWORD: 123456114514
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: festival_blessing
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  # Redis 服务
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

# 网络配置
networks:
  app-network:
    driver: bridge

# 持久化数据存储
volumes:
  mysql_data:
